dataset:
  data_path: /workspace/vu2
  dataset_name: NExTQA
  version: openended
  fps: 1
  max_num_frames: 30
  split: val
  batch_size: 2
  max_samples: 2

codex:
  prompt: ./prompts/benchmarks/nextqa_grounding.prompt
select_answer_prompt: ./prompts/gpt3/video_question.txt
fixed_code_file: ./prompts/fixed_code/nextqa_grounding.prompt

results_dir: ./results/nextqa_grounding/

gpt3:
  model: chatgpt

load_models:
  maskrcnn: True

ratio_box_area_to_image_area: 0.03
crop_larger_margin: False